Feature ldap config
YunoHost-Apps/redmine_ynh pull request #21
Opened 2023-04-08 15:17 UTC by francois-dorin

## Problem

LDAP authentication not configured by default

## Solution

Execute an SQL script at installation to create LDAP source.

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-09-13 15:25 UTC, tevino requested changes

2023-09-13 15:25 UTC, tevino commented on conf/db-ldap.sql
> +        'givenName',
The order of `sn`(surname) and `givenName` needs a swap, they are currently mapped to `attr_firstname` and `attr_lastname`.

2023-09-14 06:16 UTC, francois-dorin commented on conf/db-ldap.sql
> +        'givenName',
You're right. I will fix this soon and update this PR.

Thank you for your feedback :)

2023-09-14 06:33 UTC, tevino commented on conf/db-ldap.sql
> +        'givenName',
I haven't tried the script in the PR but a manual configuration according to the sql works.

And thank you @francois-dorin for your work :)

2023-09-18 08:12 UTC, francois-dorin commented on conf/db-ldap.sql
> +        'givenName',
I fix the inversion and updated the PR

@tevino : thank you :)

2023-10-25 20:39 UTC, ericgaspar commented
!testme

2024-02-24 20:36 UTC, OniriCorpe commented
!testme

2024-02-24 21:11 UTC, OniriCorpe commented
ah, i didn't see that it was already adde to the package by https://github.com/YunoHost-Apps/redmine_ynh/pull/23

so closing the PR

thank you, anyway ^w^

2024-02-24 21:11 UTC, closed without merging

2024-02-25 12:42 UTC, francois-dorin commented
Well, in fact my contribution seems to have been "secretly" pickup into PR #23 in a commit with message "cleaning" (cf. https://github.com/YunoHost-Apps/redmine_ynh/pull/23/commits/1fcae428eaeef8ab3ff52f18b33f4789d14f061d)

Is it a normal behavior in contribution managment ?